name: ðŸ§ª todos-action

on:
  pull_request:

permissions:
  issues: write

jobs:
  test-todos-action:
    runs-on: "ubuntu-latest"
    steps:
      - name: ðŸ“‘ Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: ðŸ§ª Run todos-action
        uses: ./todos-action
        with:
          APP_ID: ${{ vars.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          PROJECT: organization/devantler-tech/5
